name: Build and Deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build the Docker container image
      run: docker build -t docker.pkg.github.com/bjorngylling/kafka-acl-viewer/kafka-acl-viewer:latest .

    - name: Push the image to GPR
      run: |
        docker login docker.pkg.github.com -u bjorngylling -p "${GITHUB_TOKEN}"
        docker push docker.pkg.github.com/bjorngylling/kafka-acl-viewer/kafka-acl-viewer:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
